#!/usr/bin/env bats

load test_helper

checker="bin/routine-render-check"

# A render is a file whose first line declares the generator that made
# it. The fixtures build a throwaway repo root holding a bin/ with a
# generator script of our own, so the check is exercised against a
# render whose freshness the test controls rather than against this
# repository's real evidence/.
make_repo() {
  repo="$BATS_TEST_TMPDIR/repo"
  mkdir -p "$repo/bin" "$repo/evidence"
}

# Writes a generator at bin/routine-<name> printing the lines given
# after the name, under a header naming itself.
make_generator() {
  name="$1"
  shift
  {
    echo '#!/usr/bin/env bash'
    echo "echo \"# generated by bin/routine-$name at \$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
    for line in "$@"; do
      echo "echo '$line'"
    done
  } > "$repo/bin/routine-$name"
  chmod +x "$repo/bin/routine-$name"
}

# Writes a committed render with a fixed (old) timestamp in its header.
make_render() {
  name="$1"
  shift
  {
    echo "# generated by bin/routine-$name at 2020-01-01T00:00:00Z"
    for line in "$@"; do
      echo "$line"
    done
  } > "$repo/evidence/$name.txt"
}

@test "a render whose body drifted from its generator is refused" {
  make_repo
  make_generator report "alpha=1" "beta=2"
  make_render report "alpha=99" "beta=2"
  run "$ROUTINE_REPO_ROOT/$checker" "$repo/evidence/report.txt"
  [ "$status" -eq 1 ]
  case "$output" in *"report.txt"*) ;; *) false ;; esac
}

@test "a refusal names the command that refreshes the render" {
  make_repo
  make_generator report "alpha=1"
  make_render report "alpha=99"
  run "$ROUTINE_REPO_ROOT/$checker" "$repo/evidence/report.txt"
  [ "$status" -eq 1 ]
  case "$output" in *"bin/routine-report"*) ;; *) false ;; esac
}

@test "a render matching its generator passes despite an older timestamp" {
  make_repo
  make_generator report "alpha=1" "beta=2"
  make_render report "alpha=1" "beta=2"
  run "$ROUTINE_REPO_ROOT/$checker" "$repo/evidence/report.txt"
  [ "$status" -eq 0 ]
}

@test "the generator timestamp alone is never treated as drift" {
  make_repo
  make_generator report "alpha=1"
  make_render report "alpha=1"
  run "$ROUTINE_REPO_ROOT/$checker" "$repo/evidence/report.txt"
  [ "$status" -eq 0 ]
  case "$output" in *"2020-01-01"*) false ;; *) ;; esac
}

@test "a generator outside the repository bin is refused, not executed" {
  make_repo
  printf '%s\n' '#!/usr/bin/env bash' "touch $BATS_TEST_TMPDIR/executed" \
    > "$BATS_TEST_TMPDIR/evil"
  chmod +x "$BATS_TEST_TMPDIR/evil"
  printf '%s\n' "# generated by $BATS_TEST_TMPDIR/evil at 2020-01-01T00:00:00Z" \
    "alpha=1" > "$repo/evidence/report.txt"
  run "$ROUTINE_REPO_ROOT/$checker" "$repo/evidence/report.txt"
  [ "$status" -eq 1 ]
  [ ! -f "$BATS_TEST_TMPDIR/executed" ]
  case "$output" in *"generator"*) ;; *) false ;; esac
}

@test "a file carrying no generator header is not a render and is skipped" {
  make_repo
  printf '%s\n' "just a document" > "$repo/evidence/notes.md"
  run "$ROUTINE_REPO_ROOT/$checker" "$repo/evidence/notes.md"
  [ "$status" -eq 0 ]
}

@test "no argument names usage and refuses" {
  run "$ROUTINE_REPO_ROOT/$checker"
  [ "$status" -eq 2 ]
  case "$output" in *"usage"*) ;; *) false ;; esac
}

@test "a named file that does not exist is a usage error" {
  make_repo
  run "$ROUTINE_REPO_ROOT/$checker" "$repo/evidence/absent.txt"
  [ "$status" -eq 2 ]
  case "$output" in *"usage"*) ;; *) false ;; esac
}
